(ns cljnix.build-test
  (:require
    [clojure.test :refer [deftest is testing]]
    [babashka.fs :as fs]
    [cljnix.test-helpers :as h]
    [cljnix.build :as build]
    [cljnix.build.jvm :as jvm]))

;; Phase 1 Tests: Build system modularity
;; These tests ensure build functions can work with different source types

(deftest src-dirs-extraction
  (testing "Source directory extraction works independently"
    (fs/with-temp-dir [project-dir {:prefix "src_project"}]
      (let [spit-helper (h/make-spit-helper project-dir)
            deps-file (str (fs/path project-dir "deps.edn"))]
        (spit-helper "deps.edn" {:paths ["src" "resources"]})
        (let [paths (#'jvm/get-paths deps-file)]
          (is (vector? paths)
              "Paths should be a vector")
          (is (= ["src" "resources"] paths)
              "Should extract paths from deps.edn"))))))

(deftest src-dirs-default-value
  (testing "Source directory defaults to src when not specified"
    (fs/with-temp-dir [project-dir {:prefix "default_src_project"}]
      (let [spit-helper (h/make-spit-helper project-dir)
            deps-file (str (fs/path project-dir "deps.edn"))]
        (spit-helper "deps.edn" {})
        (let [paths (#'jvm/get-paths deps-file)]
          (is (= ["src"] paths)
              "Should default to [\"src\"]"))))))

(deftest parse-compile-clj-opts-transforms
  (testing "parse-compile-clj-opts handles various option types"
    (let [opts {:ns-compile ["foo.core" "bar.util"]
                :sort "topo"
                :compile-opts {:elide-meta ["doc" "file"]}
                :filter-nses ["foo.*"]
                :use-cp-file "file"}
          parsed (#'jvm/parse-compile-clj-opts opts)]
      (is (every? symbol? (:ns-compile parsed))
          "ns-compile should be converted to symbols")
      (is (keyword? (:sort parsed))
          "sort should be converted to keyword")
      (is (every? keyword? (get-in parsed [:compile-opts :elide-meta]))
          "elide-meta should be converted to keywords")
      (is (every? symbol? (:filter-nses parsed))
          "filter-nses should be converted to symbols")
      (is (keyword? (:use-cp-file parsed))
          "use-cp-file should be converted to keyword"))))

(deftest build-options-separation
  (testing "Build options are separate from dependency resolution"
    (let [lib-opts {:lib-name 'test/app
                    :version "1.0.0"}
          compile-opts {:ns-compile ['test.core]
                        :sort :topo}]
      (is (not (contains? lib-opts :ns-compile))
          "Library options shouldn't contain compilation details")
      (is (not (contains? compile-opts :lib-name))
          "Compilation options shouldn't contain library metadata")
      (is (symbol? (:lib-name lib-opts))
          "lib-name can be processed independently")
      (is (every? symbol? (:ns-compile compile-opts))
          "Compilation namespaces can be processed independently"))))

(deftest timestamp-removal-for-reproducibility
  (testing "remove-timestamp! provides reproducible builds"
    (fs/with-temp-dir [project-dir {:prefix "timestamp_project"}]
      (let [meta-dir (fs/path project-dir "META-INF" "maven" "test" "lib")
            pom-props (fs/path meta-dir "pom.properties")]
        (fs/create-dirs meta-dir)
        (spit (str pom-props)
              (str "#Generated by Maven\n"
                   "#Wed Jan 01 00:00:00 UTC 2020\n"
                   "version=1.0.0\n"
                   "groupId=test\n"
                   "artifactId=lib\n"))
        (build/remove-timestamp! (str project-dir) "test/lib")
        (let [content (slurp (str pom-props))]
          (is (not (clojure.string/includes? content "#Generated"))
              "Should remove generated comment")
          (is (not (clojure.string/includes? content "#Wed"))
              "Should remove timestamp comment")
          (is (clojure.string/includes? content "version=1.0.0")
              "Should keep version property")
          (is (clojure.string/includes? content "groupId=test")
              "Should keep groupId property"))))))

(deftest class-dir-constant
  (testing "class-dir is consistently defined"
    (is (= "target/classes" build/class-dir)
        "class-dir should be target/classes")))

(deftest parse-compile-opts-handles-empty
  (testing "parse-compile-clj-opts handles empty options"
    (let [parsed (#'jvm/parse-compile-clj-opts {})]
      (is (map? parsed)
          "Should return a map for empty options"))))

(deftest parse-compile-opts-preserves-unknown
  (testing "parse-compile-clj-opts preserves unknown keys"
    (let [opts {:unknown-key "value"
                :ns-compile ["foo.core"]}
          parsed (#'jvm/parse-compile-clj-opts opts)]
      (is (contains? parsed :unknown-key)
          "Should preserve unknown keys")
      (is (= "value" (:unknown-key parsed))
          "Should preserve unknown key values"))))
