name: tests

on:
  workflow_dispatch: # allows manual triggering
  push:
    paths-ignore:
      - "**.md"
      - "docs/**"
      - ".github/**"
    branches:
      - main
  pull_request:
    paths-ignore:
      - "**.md"
      - "docs/**"
      - ".github/**"

jobs:
  ci-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: DeterminateSystems/nix-installer-action@main

      - name: Warm Nix devShell
        run: |
          nix develop --command echo

      - name: "Tests: Unit"
        run: |
          nix develop --command tests-unit

      - name: "Tests: Integration"
        run: |
          nix develop --command tests-integration

      - name: "Tests: End-to-end"
        run: |
          nix develop --command tests-e2e
          echo "Derivations:"
          cat "/tmp/.cljnix-derivations"
