name: "Update deps"
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: "33 3 * * 1"

jobs:
  clojure-deps:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: DeterminateSystems/nix-installer-action@main

      - name: Update clj dependencies
        run: nix develop --command update-clojure-deps

      - name: Update clojure lock files
        run: nix develop --command update-lock-files

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: Update clojure dependencies
          title: Update clojure dependencies
          assignees: jlesquembre
          branch: update-clj-deps
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
          labels: |
            dependencies
            automated
